DROP TYPE IF EXISTS grocery; 

CREATE TYPE grocery AS ENUM ( 
  'Main', 
  'Snack', 
  'Lunch', 
  'Breakfast' 
);

DROP TABLE IF EXISTS shopping_list;

CREATE TABLE IF NOT EXISTS shopping_list (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price decimal(10,2) NOT NULL,
    date_added TIMESTAMP DEFAULT now() NOT NULL,
    checked BOOLEAN DEFAULT false NOT NULL,
    category grocery NOT NULL
);

DROP TABLE IF EXISTS testItems;

CREATE TABLE IF NOT EXISTS testItems (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price decimal(10,2) NOT NULL,
    date_added TIMESTAMP DEFAULT now() NOT NULL,
    checked BOOLEAN DEFAULT false NOT NULL,
    category grocery NOT NULL
);

